services:
  mkcert:
    container_name: chatster-mkcert
    build:
      context: .
      dockerfile: Dockerfile.mkcert
    networks:
      - chatster-network
    volumes:
      - ./certs:/certs
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "mkcert -key-file /certs/key.pem -cert-file /certs/cert.pem localhost 127.0.0.1 ::1",
      ]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: sh -c "npx prisma generate && npm run dev"
    environment:
      NODE_ENV: development
      SSL_CRT_FILE: ${SSL_CRT_FILE}
      SSL_KEY_FILE: ${SSL_KEY_FILE}
    volumes:
      - ./server:/app
      - ./certs:/app/certs
    depends_on:
      - mkcert

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      AUTH_TEST_EMAIL: ${AUTH_TEST_EMAIL}
      AUTH_TEST_PASSWORD: ${AUTH_TEST_PASSWORD}
      VITE_SSL_CRT_FILE: ${SSL_CRT_FILE}
      VITE_SSL_KEY_FILE: ${SSL_KEY_FILE}
    volumes:
      - ./client:/app
      - ./certs:/app/certs
    depends_on:
      - mkcert
