services:
  server:
    command: sh -c "npx prisma generate && npm run build && npm run start"

  client:
    container_name: chatster-client
    build:
      context: ./client
      dockerfile: Dockerfile.test
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        AUTH0_TEST_EMAIL: ${AUTH0_TEST_EMAIL}
        AUTH0_TEST_PASSWORD: ${AUTH0_TEST_PASSWORD}
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      server:
        condition: service_healthy
