services:
  postgres:
    image: postgres:latest
    container_name: chatster-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - chatster-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: chatster-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/test:/app/test
    networks:
      - chatster-network
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npm run dev"

networks:
  chatster-network:
    driver: bridge

volumes:
  postgres-data:
