services:
  mkcert:
    container_name: chatster-mkcert
    build:
      context: .
      dockerfile: Dockerfile.mkcert
    networks:
      - chatster-network
    volumes:
      - ./certs:/certs
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "mkcert -key-file /certs/key.pem -cert-file /certs/cert.pem localhost 127.0.0.1 ::1",
      ]

  server:
    command: sh -c "npx prisma generate && npm run build && npm run start"
    environment:
      NODE_ENV: development
      SSL_CRT_FILE: /app/certs/cert.pem
      SSL_KEY_FILE: /app/certs/key.pem
    volumes:
      - ./certs:/app/certs
    depends_on:
      - mkcert

  client:
    container_name: chatster-client
    build:
      context: ./client
      dockerfile: Dockerfile.test
      args:
        AUTH_TEST_EMAIL: ${AUTH_TEST_EMAIL}
        AUTH_TEST_PASSWORD: ${AUTH_TEST_PASSWORD}
        VITE_BASE_URL: ${CLIENT_BASE_URL}
        VITE_SERVER_BASE_URL: ${SERVER_BASE_URL_BY_HOSTNAME}
        VITE_SSL_CRT_FILE: /app/certs/cert.pem
        VITE_SSL_KEY_FILE: /app/certs/key.pem
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./certs:/app/certs
    depends_on:
      - mkcert
