services:
  postgres:
    image: postgres:latest
    container_name: chatster-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - chatster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  server:
    container_name: chatster-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - chatster-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: ${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fk ${SERVER_BASE_URL}/api || exit 1"]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 10s

  client:
    container_name: chatster-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - chatster-network
    environment:
      VITE_SERVER_BASE_URL: ${SERVER_BASE_URL}
      VITE_BASE_URL: ${CLIENT_BASE_URL}
    depends_on:
      server:
        condition: service_healthy

networks:
  chatster-network:
    driver: bridge
