services:
  server:
    command: sh -c "npx prisma generate && npm run build && npm run start"

  client:
    container_name: chatster-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      server:
        condition: service_healthy
